name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install Lint
      run: true go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      
    - name: Build
      run: go build -v ./...
      
    - name: Lint
      run: true $(go env GOPATH)/bin/golangci-lint run -v

    - name: Test
      run: go test -v ./...
      
    - name: Deploy GCP_SERVICE_ACCESS_KEY_JSON
      run: date
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCESS_KEY_JSON }}'
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0

    - name: Use gcloud CLI
      run: gcloud info
      
    # - uses: actions/checkout@v1
    - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: exercise-loan-calculator
          APPLICATION_CREDENTIALS: ${{secrets.GCP_SERVICE_ACCESS_KEY_JSON}}
        with:
          args: app deploy app.yaml


    - id: Deploy
      uses: google-github-actions/deploy-appengine@v0.4.0
