name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Build
      run: go build -v ./...
      
    - name: Install Lint
      run: true go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

    - name: Lint
      run: true $(go env GOPATH)/bin/golangci-lint run -v

    - name: Test
      run: go test -v ./...
      
    - id: Auth
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCESS_KEY_JSON }}'
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      
    - name: Deploy
      run: gcloud app deploy --quiet
