name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Test
      run: go test -cover -v -cover ./go/...
      
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest
  
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0

    - id: Auth
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCESS_KEY_JSON }}'
              
    - name: Deploy
      run: gcloud app deploy --quiet
          
    - name: Integration Test
      run: go test -v 
